
# ========= Border =========
file_panel_border = '#e5d5b1'
sidebar_border = '#e5d5b1'
footer_border = '#e5d5b1'

# ========= Border Active =========
file_panel_border_active = '#a5cab8'
sidebar_border_active = '#a5cab8'
footer_border_active = '#a5cab8'
modal_border_active = '#a5cab8'

# ========= Background (bg) =========
full_screen_bg = '#131515'
file_panel_bg = '#131515'
sidebar_bg = '#131515'
footer_bg = '#131515'
modal_bg = '#131515'

# ========= Foreground (fg) =========
full_screen_fg = '#F1E4C2'
file_panel_fg = '#F1E4C2'
sidebar_fg = '#F1E4C2'
footer_fg = '#F1E4C2'
modal_fg = '#F1E4C2'

# ========= Special Color =========
cursor = '#F1E4C2'
correct = '#b6c36f'
error = '#f16e65'
hint = '#8ecd84'
cancel = '#f16e65'
gradient_color = ['#131515', "#393939"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#131515'
file_panel_top_path = '#393939'
file_panel_item_selected_fg = '#393939'
file_panel_item_selected_bg = '#131515'

# ========= Sidebar Special Items =========
sidebar_title = '#393939'
sidebar_item_selected_fg = '#393939'
sidebar_item_selected_bg = '#131515'
sidebar_divider = '#e5d5b1'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#f16e65'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#b6c36f'
