[meta]
version = 1
name = "Omarchy"
description = "Follow your Omarchy system theme."
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
background = "#131515"
foreground = "#F1E4C2"
secondary_background = "#181a1a"
border = "#393939"
accent = "#ef944d"

[colors.list.item.hover]
background = "#1d1f1f"
foreground = "#F1E4C2"

[colors.list.item.selection]
background = "#222424"
foreground = "#F1E4C2"

[colors.accents]
blue = "#a5cab8"
green = "#b6c36f"
magenta = "#e9869a"
orange = "#ef944d"
purple = "#e396a4"
red = "#f16e65"
yellow = "#efbe71"
cyan = "#8ecd84"
